# Generated by Django 4.2.5 on 2023-10-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='Fecha de Publicacion')),
                ('descripcion', models.CharField(max_length=600)),
                ('img_phone', models.ImageField(default='images_tec/teclado1.jpg', upload_to='images_tec/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.categoria')),
            ],
        ),
    ]
